### ISSUE TITLE
Cannot change publicPath in vue

### ISSUE THREAD

**Issue by juanise** [juanise/jvjr-docker-env#1]
if you try to use jvjr-docker-env in vue.config.js it will fail.

Steps to reproduce:
1. Require library on vue.config.js
 ```
var EnvProvider = require('jvjr-docker-env');

module.exports = {
  publicPath: EnvProvider.value('PUBLIC_PATH_CONFIG'), // process.env.VUE_APP_PUBLIC_PATH,

```

2. Try to start the app
 ```npm start```

``` 
 ERROR  Error loading vue.config.js:
 ERROR  SyntaxError: Unexpected identifier
/home/user/WebstormProjects/myproject/node_modules/jvjr-docker-env/EnvProvider.js:1
import dotenv from 'dotenv';
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```

**Comment by juanise** [comment]
Commit dfae2fad4c2b8f5a093651c9d184e84cbfa14036
